[package]
name = "exer9"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "~0.8"

[dev-dependencies]
criterion = { version = "~0.5", features = ["html_reports"] }

[[bench]]
name = "iterators_benchmark"
harness = false
